name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for Gradlew
        run: chmod +x gradlew  # Füge diesen Schritt hinzu

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 16

      - name: Clean and build
        run: ./gradlew clean test --info --stacktrace
